# Generated by Django 5.1.2 on 2024-10-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
